### ISSUE TITLE
Backgrounds of mod categories not re-colored

### ISSUE THREAD

**Issue by ghost** [Ikszyon/MegaHack-Recolor#1]
Latest version, loaded with quickldr (at the splash, otherwise it crashes)
After changing the color it looks like so:
![obraz](https://user-images.githubusercontent.com/65465165/224381985-6a725430-973a-4032-bad3-62622232ac86.png)

**Comment by Ikszyon** [comment]
sorry for taking so long but I forgor to check the issues tab,
this is a known bug and its fixed in the next update.
