### ISSUE TITLE
GD memory manip

### ISSUE THREAD

**Issue by om3ga6400** [Ikszyon/MegaHack-Recolor#2]
Where can i get the gd memory manip mod?

**Comment by Ikszyon** [comment]
Its a mod I made for testing purposes to easily patch a modules memory at a given offset, if you didnt understand any of that it'll be useless to you. https://cdn.discordapp.com/attachments/1028291642979000332/1028294466412482611/memdumper.dll

**Comment by om3ga6400** [comment]
thank you very much im a dev also and i wanna try modding gd!
